# Generated by Django 4.2.16 on 2024-12-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("phone", models.CharField(default=7, max_length=11, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SalesmanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("phone", models.CharField(default=7, max_length=11, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("hiring_date", models.DateField()),
                (
                    "job_position",
                    models.CharField(
                        choices=[
                            ("sal_man", "Продавец"),
                            ("sen_sal_man", "Старший продавец"),
                            ("head_sal_dep", "Руководитель отдела продаж"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sales", models.DateField()),
                ("quantity", models.PositiveSmallIntegerField()),
                ("sum_sales", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firma.buyermodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firma.productmodel",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firma.salesmanmodel",
                    ),
                ),
            ],
        ),
    ]
