# Generated by Django 4.2.16 on 2024-12-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyermodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="buyermodel",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="buyermodel",
            name="phone",
            field=models.CharField(
                default=7, max_length=11, unique=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="buyermodel",
            name="surname",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="salesinfomodel",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="firma.buyermodel",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="salesinfomodel",
            name="date_sales",
            field=models.DateField(verbose_name="Дата продажи"),
        ),
        migrations.AlterField(
            model_name="salesinfomodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="firma.productmodel",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="salesinfomodel",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="salesinfomodel",
            name="salesman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="firma.salesmanmodel",
                verbose_name="Продавец",
            ),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="hiring_date",
            field=models.DateField(verbose_name="Дата трудоустройства"),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="job_position",
            field=models.CharField(
                choices=[
                    ("sal_man", "Продавец"),
                    ("sen_sal_man", "Старший продавец"),
                    ("head_sal_dep", "Руководитель отдела продаж"),
                ],
                max_length=30,
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="phone",
            field=models.CharField(
                default=7, max_length=11, unique=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="salesmanmodel",
            name="surname",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
    ]
