# Generated by Django 4.2.16 on 2024-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="email",
            field=models.EmailField(max_length=128, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="note",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="Телефон"),
        ),
    ]
