# Generated by Django 4.2.16 on 2024-12-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "phone_book",
            "0002_alter_phonebook_email_alter_phonebook_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="note",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.CharField(default=7, max_length=11, verbose_name="Телефон"),
        ),
    ]
