# Generated by Django 4.2.16 on 2024-12-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('web_site', models.URLField(unique=True)),
                ('phone', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
